# -*- coding: utf-8 -*-
"""OpenCV_session1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11r_bdryhOOy60Q18T1CB97wLSoXzKtGz
"""



"""## Install the packages"""

!pip install opencv-python

import cv2
 from google.colab.patches import cv2_imshow

"""## Load and read the image"""

image_cv = cv2.imread("/content/11.jpeg")
cv2_imshow(image_cv)

image_cv.shape

b,g,r = cv2.split(image_cv)

b

g

r

cv2_imshow(b)

cv2_imshow(g)

cv2_imshow(r)

import matplotlib.pyplot as plt
plt.imshow(r)

plt.imshow(g)

plt.imshow(r,cmap = "gray")

plt.imshow(r,cmap = "Reds")

plt.imshow(g,cmap = "Greens")

plt.imshow(b,cmap = "Blues")

